name: azpwsh
description: 'Action to execute PowerShell scripts.'
inputs:
  inlineScript:
    description: 'Specify the Az PowerShell script here.'
    required: true
  azPSVersion:
    description: '123'
    required: false
runs:
  using: "docker"
  image: "dockerfile"
  args:
    - -inlineScript
    - ${{ inputs.inlineScript }}
    - -script
    - ${{ inputs.script }}
    - -azPSVersion
    - ${{ inputs.azPSVersion }}