name: azpwsh
description: 'Action to execute PowerShell scripts.'
inputs:
  inlineScript:
    description: 'Specify the Az PowerShell script here.'
    required: true
  azPSVersion:
    description: "Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify 'latest'."
    required: false
runs:
  using: "docker"
  image: "dockerfile"
  args:
    - -inlineScript
    - ${{ inputs.inlineScript }}
    - -azPSVersion
    - ${{ inputs.azPSVersion }}